context("test parsing of R expressions into C++ code")

test_that("Inavlid expressions are detected and errors triggered in function exp_to_stan",{
  expect_error(generateCpp(quote(params[10]), 2), "Parameter params\\[10\\] goes beyond the number of parameters specified.")
  expect_error(generateCpp(quote(params[7]), c(1,2,3,4,5)), "Parameter params\\[7\\] goes beyond the number of parameters specified.")
  expect_error(generateCpp(quote(params[0]), 1), "Parameter params\\[0\\] goes beyond the number of parameters specified.")
  expect_error(generateCpp(quote(params[1] + t[1]), 1), "Invalid expression: t\\[1\\]")
  expect_error(generateCpp(quote(t1), 1), "Invalid expression: t1")
  expect_error(generateCpp(quote(params[-1] + 2), 5), "Invalid expression: params\\[-1\\]")
  expect_error(generateCpp(quote(t*5 + params[-6]), 5), "Invalid expression: params\\[-6\\]")
  expect_error(generateCpp(quote(params[abcd]), 1), "Invalid expression: params\\[abcd\\]")
  expect_error(generateCpp(quote(params[]), 5), "Invalid expression: params\\[\\]")
  expect_error(generateCpp(quote(params[t]), 5), "Invalid expression: params\\[t\\]")
  expect_error(generateCpp(quote(params[1]*t[5]), 5), "Invalid expression: t\\[5\\]")
  expect_error(generateCpp(quote(params[1+1]), 5), "Invalid expression: params\\[1 \\+ 1\\]")
  expect_error(generateCpp(quote(params[3] + params12),c(4,5,6)), "Invalid expression: params12")
  expect_error(generateCpp(quote(params[[3]]), 5), "Invalid expression: params\\[\\[3\\]\\]")
  expect_error(generateCpp(quote("hi mom"), 5), "Invalid expression: \"hi mom\"")
  expect_error(generateCpp(quote(params[2] & t), c(3,4,5)), "Invalid expression: params\\[2\\] & t")
  expect_error(generateCpp(quote(c(1)), 5), "Invalid expression: c\\(1\\)")
  expect_error(generateCpp(quote(exp(params[1],params[3])), 5), "unary function applied to wrong number of parameters")
  expect_error(generateCpp(quote(log(params[1],params[3], params[2])), 5), "unary function applied to wrong number of parameters")
  expect_error(generateCpp(quote(sin()), 5), "unary function applied to wrong number of parameters")
})

test_that("Valid expressions are correctly translated to C++ by generateCpp",{
  expect_equal(generateCpp(quote(params[1]), 5), "5.000000")
  expect_equal(generateCpp(quote(t*5), c(1,2,3)), "( t ) * ( 5 )")
  expect_equal(generateCpp(quote(exp(params[3]) + log(t)), c(1,2,17)), "( exp(17.000000) ) + ( log(t) )")
  expect_equal(generateCpp(quote(log(t^4)*(params[5]*(sin(t*params[4])*params[1]))),c(0,.5,1.0,1.75,3.6)), "( log(( t ) ^ ( 4 )) ) * ( ( 3.600000 ) * ( ( sin(( t ) * ( 1.750000 )) ) * ( 0.000000 ) ) )")
  expect_equal(generateCpp(quote(params[1]*exp(t*exp(1)*params[2])), c(5,6)), "( 5.000000 ) * ( exp(( ( t ) * ( exp(1) ) ) * ( 6.000000 )) )")
})

test_that("Inavlid expressions are detected and errors triggered in function isConst",{
  expect_error(isConst(quote(params[1] + t[1])), "Invalid expression: t\\[1\\]")
  expect_error(isConst(quote(t1)), "Invalid expression: t1")
  expect_error(isConst(quote(params[-1] + 2)), "Invalid expression: params\\[-1\\]")
  expect_error(isConst(quote(t*5 + params[-6])), "Invalid expression: params\\[-6\\]")
  expect_error(isConst(quote(params[abcd])), "Invalid expression: params\\[abcd\\]")
  expect_error(isConst(quote(params[])), "Invalid expression: params\\[\\]")
  expect_error(isConst(quote(params[t])), "Invalid expression: params\\[t\\]")
  expect_error(isConst(quote(params[1]*t[5])), "Invalid expression: t\\[5\\]")
  expect_error(isConst(quote(params[1+1])), "Invalid expression: params\\[1 \\+ 1\\]")
  expect_error(isConst(quote(params[3] + params12)), "Invalid expression: params12")
  expect_error(isConst(quote(params[[3]])), "Invalid expression: params\\[\\[3\\]\\]")
  expect_error(isConst(quote("hi mom")), "Invalid expression: \"hi mom\"")
  expect_error(isConst(quote(params[2] & t)), "Invalid expression: params\\[2\\] & t")
  expect_error(isConst(quote(c(1))), "Invalid expression: c\\(1\\)")
  expect_error(isConst(quote(exp(params[1],params[3]))), "unary function applied to wrong number of parameters")
  expect_error(isConst(quote(log(params[1],params[3], params[2]))), "unary function applied to wrong number of parameters")
  expect_error(isConst(quote(sin())), "unary function applied to wrong number of parameters")
})


test_that("IsConst correctly recognizes whether expressions depend on time",{
  expect_equal(isConst(quote(params[1])), T)
  expect_equal(isConst(quote(params[1]*t)), F)
  expect_equal(isConst(quote(t)), F)
  expect_equal(isConst(quote(sin(4*t))), F)
  expect_equal(isConst(quote(4*params[8])), T)
  expect_equal(isConst(quote(8.005*params[3] + 0.0001*log(t))), F)
  expect_equal(isConst(quote(2*params[1] + 4*params[2]^2 + 8*params[3]^3)), T)
  expect_equal(isConst(quote(params[1] + params[2]*t + params[3]*t^2)), F)
})

