# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' sexp_type
#'
#' sexp_type
#'
#' @export
sexp_type <- function(x) {
    .Call('_estipop_sexp_type', PACKAGE = 'estipop', x)
}

#' gmbp3
#'
#' gmbp3
#'
#' @export
gmbp3 <- function(observations, file, initial, transitions, stops, silence, seed = NULL) {
    .Call('_estipop_gmbp3', PACKAGE = 'estipop', observations, file, initial, transitions, stops, silence, seed)
}

#' test
#'
#' test
#'
#' @export
test <- function(a, dt = NULL, initial = NULL) {
    .Call('_estipop_test', PACKAGE = 'estipop', a, dt, initial)
}

#' zee
#'
#' zee
#'
#' @export
zee <- function(a) {
    .Call('_estipop_zee', PACKAGE = 'estipop', a)
}

#' t2
#'
#' t2
#'
#' @export
t2 <- function(custom_distribution_file = NULL) {
    .Call('_estipop_t2', PACKAGE = 'estipop', custom_distribution_file)
}

#' timeDepBranch
#'
#' timeDepBranch
#'
#' @export
timeDepBranch <- function(observations, file, initial, transitions, stops, silence, seed = NULL) {
    .Call('_estipop_timeDepBranch', PACKAGE = 'estipop', observations, file, initial, transitions, stops, silence, seed)
}

