# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' gmbp3
#'
#' gmbp3
#'
#' @export
gmbp3 <- function(time, file, initial, transitions, stops, silence, seed = NULL) {
    .Call('_gmbp_gmbp3', PACKAGE = 'gmbp', time, file, initial, transitions, stops, silence, seed)
}

#' test
#'
#' test
#'
#' @export
test <- function(a) {
    .Call('_gmbp_test', PACKAGE = 'gmbp', a)
}

#' t2
#'
#' t2
#'
#' @export
t2 <- function(custom_distribution_file = NULL) {
    .Call('_gmbp_t2', PACKAGE = 'gmbp', custom_distribution_file)
}

#' timeDepBranch
#'
#' timeDepBranch
#'
#' @export
timeDepBranch <- function(time, file, initial, transitions, stops, silence) {
    .Call('_gmbp_timeDepBranch', PACKAGE = 'gmbp', time, file, initial, transitions, stops, silence)
}

